import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MicroAppContextProvider } from "@/src/app/micro-app-context-provider";
import { RecoilContextProvider } from "@/src/app/recoil-context-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RecoilContextProvider>
      <html lang="en">
        <body className={inter.className}>
          <MicroAppContextProvider>{children}</MicroAppContextProvider>
        </body>
      </html>
    </RecoilContextProvider>
  );
}
